# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-01 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blood_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('pin_code', models.IntegerField(max_length=10)),
                ('contact1', models.IntegerField(max_length=10)),
                ('contact2', models.IntegerField(max_length=10)),
                ('date', models.DateField()),
                ('blood_group', models.CharField(max_length=3)),
            ],
        ),
    ]
